### PR TITLE
Ongoing: Helping fixing all lint errors

### PR DESCRIPTION
**Pull request by Swopper050**

### CODE REVIEW

**Comment by Swopper050** [comment]
@wipsel Fixed all errors except the oness about dynamic errors (probably need your help with that a bit) and a handful others which I did not know how to fix yet.

Maybe it's a good idea to merge it, then we can finish up with the dynamic error lint errors.

**Comment by wipsel** [comment]
@Swopper050 I think that is a good idea. The pull request lgtm. What were the "others" you could not fix? Maybe I can fix them before we merge?

**Comment by Swopper050** [comment]
@wipsel These were the remaining errors

```
ops/opset13/opset13.go:45:2: Consider pre-allocating `opList` (prealloc)
	var opList []string
	^
ops/opset13/prelu.go:44:13: type assertion must be checked (forcetypeassert)
		calcPRelu(y.Data().([]float32), x.Data().([]float32), slope.Data().([]float32))
		          ^
ops/opset13/prelu.go:46:13: type assertion must be checked (forcetypeassert)
		calcPRelu(y.Data().([]float64), x.Data().([]float64), slope.Data().([]float64))
		          ^
ops/opset13/prelu.go:48:13: type assertion must be checked (forcetypeassert)
		calcPRelu(y.Data().([]uint32), x.Data().([]uint32), slope.Data().([]uint32))
		          ^
ops/opset13/prelu.go:50:13: type assertion must be checked (forcetypeassert)
		calcPRelu(y.Data().([]uint64), x.Data().([]uint64), slope.Data().([]uint64))
		          ^
ops/opset13/prelu.go:52:13: type assertion must be checked (forcetypeassert)
		calcPRelu(y.Data().([]int32), x.Data().([]int32), slope.Data().([]int32))
		          ^
ops/opset13/prelu.go:54:13: type assertion must be checked (forcetypeassert)
		calcPRelu(y.Data().([]int64), x.Data().([]int64), slope.Data().([]int64))
ops/errors.go:175:5: error-naming: error var UnknownOperatorTypeError should have name of the form ErrFoo (revive)
var UnknownOperatorTypeError = errors.New("unknown operator type")
```

**Comment by Swopper050** [comment]
@wipsel fixed all lints, only tests remaining

**Pull request merged**
